
Load the fetch_california_housing dataset from sklearn. Split the data using train_test_split with test_size = 0.2 and random_state as 1. Train the following models using the training data and calculate the R2 Score and Root Mean Squared Error (RMSE) on the test data.

- Model 1: Linear Regression

- Model 2: AdaBoost Regressor with random state = 1

- Model 3: Decision Tree Regressor with random state = 1


Choose the appropriate option:



(A) r2_score (Model 2) > r2_score (Model 1) > r2_score (Model 3)

(B) r2_score (Model 3) > r2_score (Model 1) > r2_score (Model 2)

(C) RMSE (Model 2) > RMSE (Model 1) > RMSE (Model 3)

(D) RMSE (Model 3) > RMSE (Model 1) > RMSE (Model 2)

In [1]:
# Import required libraries
from sklearn.datasets import fetch_california_housing
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import AdaBoostRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.metrics import r2_score, mean_squared_error
import numpy as np

# Load dataset
data = fetch_california_housing()
X = data.data
y = data.target

# Train-test split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=1
)

# -----------------------------
# Model 1: Linear Regression
# -----------------------------
lr = LinearRegression()
lr.fit(X_train, y_train)
y_pred_lr = lr.predict(X_test)

r2_lr = r2_score(y_test, y_pred_lr)
rmse_lr = np.sqrt(mean_squared_error(y_test, y_pred_lr))

# -----------------------------
# Model 2: AdaBoost Regressor
# -----------------------------
ada = AdaBoostRegressor(random_state=1)
ada.fit(X_train, y_train)
y_pred_ada = ada.predict(X_test)

r2_ada = r2_score(y_test, y_pred_ada)
rmse_ada = np.sqrt(mean_squared_error(y_test, y_pred_ada))

# -----------------------------
# Model 3: Decision Tree
# -----------------------------
dt = DecisionTreeRegressor(random_state=1)
dt.fit(X_train, y_train)
y_pred_dt = dt.predict(X_test)

r2_dt = r2_score(y_test, y_pred_dt)
rmse_dt = np.sqrt(mean_squared_error(y_test, y_pred_dt))

# -----------------------------
# Print Results
# -----------------------------
print("R2 Scores:")
print(f"Linear Regression: {r2_lr:.4f}")
print(f"AdaBoost Regressor: {r2_ada:.4f}")
print(f"Decision Tree: {r2_dt:.4f}")

print("\nRMSE:")
print(f"Linear Regression: {rmse_lr:.4f}")
print(f"AdaBoost Regressor: {rmse_ada:.4f}")
print(f"Decision Tree: {rmse_dt:.4f}")

# -----------------------------
# Compare
# -----------------------------
print("\nComparisons:")
print("R2 ranking:", sorted(
    [("LR", r2_lr), ("ADA", r2_ada), ("DT", r2_dt)],
    key=lambda x: x[1], reverse=True
))

print("RMSE ranking:", sorted(
    [("LR", rmse_lr), ("ADA", rmse_ada), ("DT", rmse_dt)],
    key=lambda x: x[1]
))

R2 Scores:
Linear Regression: 0.5966
AdaBoost Regressor: 0.3945
Decision Tree: 0.6179

RMSE:
Linear Regression: 0.7274
AdaBoost Regressor: 0.8912
Decision Tree: 0.7080

Comparisons:
R2 ranking: [('DT', 0.617856045060232), ('LR', 0.5965968374812278), ('ADA', 0.39454499317099845)]
RMSE ranking: [('DT', np.float64(0.7079934509704039)), ('LR', np.float64(0.7274202599183918)), ('ADA', np.float64(0.8911620439887686))]


In [2]:
# 1. Load the dataset
data = fetch_california_housing()
X = data.data
y = data.target

# 2. Split the data
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=1
)

# Initialize models
models = {
    "Model 1: Linear Regression": LinearRegression(),
    "Model 2: AdaBoost Regressor": AdaBoostRegressor(random_state=1),
    "Model 3: Decision Tree Regressor": DecisionTreeRegressor(random_state=1)
}

results = {}

# 3. Train and Evaluate
for name, model in models.items():
    model.fit(X_train, y_train)
    predictions = model.predict(X_test)

    r2 = r2_score(y_test, predictions)
    rmse = np.sqrt(mean_squared_error(y_test, predictions))

    results[name] = {"R2": r2, "RMSE": rmse}

# 4. Display results
results_df = pd.DataFrame(results).T
print(results_df)

                                        R2      RMSE
Model 1: Linear Regression        0.596597  0.727420
Model 2: AdaBoost Regressor       0.394545  0.891162
Model 3: Decision Tree Regressor  0.617856  0.707993


Common Instructions for questions 2 & 3


Load the Iris Dataset from sklearn. Split the data using train_test_split with test_size = 0.33 and random_state as 1. Train the Logistic Regression model (with random state as 1) on the training data and make predictions on the test data. Print the confusion matrix and the classification report


How many samples has the model misclassified?

In [3]:
# Import libraries
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix, classification_report
import numpy as np

# Load dataset
iris = load_iris()
X = iris.data
y = iris.target

# Train-test split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.33, random_state=1
)

# Train Logistic Regression model
model = LogisticRegression(random_state=1, max_iter=200)
model.fit(X_train, y_train)

# Predictions
y_pred = model.predict(X_test)

# Confusion Matrix
cm = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:\n", cm)

# Classification Report
print("\nClassification Report:\n", classification_report(y_test, y_pred))

# Misclassified samples
misclassified = np.sum(y_test != y_pred)
print("\nNumber of misclassified samples:", misclassified)

Confusion Matrix:
 [[17  0  0]
 [ 0 18  1]
 [ 0  0 14]]

Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        17
           1       1.00      0.95      0.97        19
           2       0.93      1.00      0.97        14

    accuracy                           0.98        50
   macro avg       0.98      0.98      0.98        50
weighted avg       0.98      0.98      0.98        50


Number of misclassified samples: 1


In [4]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix, classification_report

# 1. Load the dataset
iris = load_iris()
X, y = iris.data, iris.target

# 2. Split the data
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.33, random_state=1
)

# 3. Initialize and train the Logistic Regression model
# We increase max_iter to ensure convergence on this dataset
model = LogisticRegression(random_state=1, max_iter=200)
model.fit(X_train, y_train)

# 4. Make predictions
y_pred = model.predict(X_test)

# 5. Print results
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))
print("\nClassification Report:")
print(classification_report(y_test, y_pred, target_names=iris.target_names))

# 6. Calculate misclassified samples
misclassified = (y_test != y_pred).sum()
print(f"\nNumber of misclassified samples: {misclassified}")

Confusion Matrix:
[[17  0  0]
 [ 0 18  1]
 [ 0  0 14]]

Classification Report:
              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        17
  versicolor       1.00      0.95      0.97        19
   virginica       0.93      1.00      0.97        14

    accuracy                           0.98        50
   macro avg       0.98      0.98      0.98        50
weighted avg       0.98      0.98      0.98        50


Number of misclassified samples: 1


What is the recall for class 1? [Answer to two decimal places] (Note that the classes are 0 , 1, 2)


In [5]:
# Import libraries
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix

# Load dataset
iris = load_iris()
X = iris.data
y = iris.target

# Split data
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.33, random_state=1
)

# Train model
model = LogisticRegression(random_state=1, max_iter=200)
model.fit(X_train, y_train)

# Predictions
y_pred = model.predict(X_test)

# Confusion matrix
cm = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:\n", cm)

# Recall for class 1
TP = cm[1][1]
FN = cm[1][0] + cm[1][2]

recall_class1 = TP / (TP + FN)
print("\nRecall for class 1:", round(recall_class1, 2))

Confusion Matrix:
 [[17  0  0]
 [ 0 18  1]
 [ 0  0 14]]

Recall for class 1: 0.95


In [6]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report

# Load the dataset
iris = load_iris()
X, y = iris.data, iris.target

# Split the data
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.33, random_state=1
)

# Initialize and train the Logistic Regression model
model = LogisticRegression(random_state=1, max_iter=200)
model.fit(X_train, y_train)

# Make predictions
y_pred = model.predict(X_test)

# Get classification report as a dictionary
report = classification_report(y_test, y_pred, output_dict=True)

# Extract recall for class 1
recall_class_1 = report['1']['recall']
print(f"{recall_class_1=}")

recall_class_1=0.9473684210526315


Common Instructions for questions 4 & 5


Load the train subset of '20newsgroups' data with return_X_y = True. Vectorize X using TfidfVectorizer.


1 point
Which of the following options represent the shape of the fitted and transformed data X?

(A) (11310, 130507)

(B) (21314, 190807)

(C) (11514, 160107)

(D) (11314, 130107)

In [7]:
# Import libraries
from sklearn.datasets import fetch_20newsgroups
from sklearn.feature_extraction.text import TfidfVectorizer

# Load TRAIN subset
X, y = fetch_20newsgroups(subset='train', return_X_y=True)

# Initialize TF-IDF Vectorizer
vectorizer = TfidfVectorizer()

# Fit and transform
X_tfidf = vectorizer.fit_transform(X)

# Print shape
print("Shape of TF-IDF matrix:", X_tfidf.shape)

Shape of TF-IDF matrix: (11314, 130107)


In [8]:
from sklearn.datasets import fetch_20newsgroups
from sklearn.feature_extraction.text import TfidfVectorizer

# 1. Load the train subset
# return_X_y=True returns a tuple (data, target) instead of a Bunch object
X, y = fetch_20newsgroups(subset='train', return_X_y=True)

# 2. Initialize the Vectorizer
# Default settings: lowercase=True, token_pattern=r"(?u)\b\w\w+\b", etc.
vectorizer = TfidfVectorizer()

# 3. Fit and Transform the data
X_tfidf = vectorizer.fit_transform(X)

# 4. Print the shape of the resulting sparse matrix
print(f"The shape of the transformed data is: {X_tfidf.shape}")

The shape of the transformed data is: (11314, 130107)



Split the vectorized data and label into train and validation sets using train_test_split with test_size = 0.3 and random_state = 1. Train a MultinomialNB model on the training dataset and compute the score on the validation set. Enter the score obtained.


In [9]:
# Import libraries
from sklearn.datasets import fetch_20newsgroups
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB

# Load TRAIN subset
X, y = fetch_20newsgroups(subset='train', return_X_y=True)

# Vectorize using TF-IDF
vectorizer = TfidfVectorizer()
X_tfidf = vectorizer.fit_transform(X)

# Train-validation split
X_train, X_val, y_train, y_val = train_test_split(
    X_tfidf, y, test_size=0.3, random_state=1
)

# Train Multinomial Naive Bayes
model = MultinomialNB()
model.fit(X_train, y_train)

# Compute score (accuracy)
score = model.score(X_val, y_val)

print("Validation Accuracy:", round(score, 4))

Validation Accuracy: 0.8274


In [10]:
from sklearn.datasets import fetch_20newsgroups
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB

# 1. Load the train subset
X_raw, y_raw = fetch_20newsgroups(subset='train', return_X_y=True)

# 2. Vectorize the data
vectorizer = TfidfVectorizer()
X_tfidf = vectorizer.fit_transform(X_raw)

# 3. Split into training and validation sets
X_train, X_val, y_train, y_val = train_test_split(
    X_tfidf, y_raw, test_size=0.3, random_state=1
)

# 4. Train the Multinomial Naive Bayes model
clf = MultinomialNB()
clf.fit(X_train, y_train)

# 5. Compute and print the score
score = clf.score(X_val, y_val)
print(f"Validation Score: {score}")

Validation Score: 0.8273932253313696
